"""
config.py — Single source of truth for all paths and hyperparameters.

All other pipeline stages import from here. Change a path or param once,
and it takes effect everywhere.
"""

import os

# ── Root directories ──────────────────────────────────────────────────────────
PROJECT_ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_DATA_ROOT = os.path.join(PROJECT_ROOT, "src", "data")
OUTPUTS_ROOT  = os.path.join(PROJECT_ROOT, "outputs")

# ── Raw input paths (never modified by the pipeline) ─────────────────────────
SNAP_FILE         = os.path.join(RAW_DATA_ROOT, "SNAPApps", "SNAPData.csv")
COUNTY_METRO_FILE = os.path.join(RAW_DATA_ROOT, "county_to_metro.csv")
POP_FILE          = os.path.join(RAW_DATA_ROOT, "popData.csv")
INCOME_FILE       = os.path.join(RAW_DATA_ROOT, "MedianIncome.csv")
TRENDS_DIR        = os.path.join(RAW_DATA_ROOT, "trends")
LAUS_FILE         = os.path.join(TRENDS_DIR, "laus_county_unemployment_2017_2025.csv")

# Maps pipeline keyword name → actual folder name under TRENDS_DIR.
# Each folder contains one sub-directory per DMA, with year-chunk CSVs inside.
TRENDS_FOLDER_MAP = {
    "CalFresh":    "CalFresh2017-2025",
    "FoodBank":    "Food bank 2017-2025",
    "FoodStamps":  "Food Stamps 2017-2025",
    "SNAPTopic":   "SNAP Topic 2017-2025",
}
PREDICTION_DIR    = os.path.join(RAW_DATA_ROOT, "prediction")

# ── Generated output paths ────────────────────────────────────────────────────
TRAINING_DATA_CSV      = os.path.join(OUTPUTS_ROOT, "data", "training_data.csv")
FEATURES_CSV            = os.path.join(OUTPUTS_ROOT, "data", "features.csv")
FEATURE_REGISTRY_CSV    = os.path.join(OUTPUTS_ROOT, "data", "feature_registry.csv")
FEATURE_DICTIONARY_CSV  = os.path.join(OUTPUTS_ROOT, "data", "feature_dictionary.csv")
SCALING_PARAMS_JSON    = os.path.join(OUTPUTS_ROOT, "data", "trend_scaling_params.json")
MODEL_PKL              = os.path.join(OUTPUTS_ROOT, "models", "xgboost_tuned.pkl")
INSAMPLE_METRICS_JSON  = os.path.join(OUTPUTS_ROOT, "metrics", "insample_metrics.json")
FEATURE_IMPORTANCE_CSV = os.path.join(OUTPUTS_ROOT, "metrics", "feature_importance.csv")
WF_OVERALL_JSON        = os.path.join(OUTPUTS_ROOT, "metrics", "walkforward_overall.json")
WF_PER_MONTH_CSV       = os.path.join(OUTPUTS_ROOT, "metrics", "walkforward_per_month.csv")
# Per-county-month walk-forward predictions (county, date, predicted_rate, actual_rate).
# Generated by stage4_evaluate.py; consumed by evaluate_alerts.py and calibrate_alpha.py
# so those scripts use the model's actual out-of-sample predictions instead of actual rates.
WF_PREDICTIONS_CSV     = os.path.join(OUTPUTS_ROOT, "metrics", "walkforward_predictions.csv")
PREDICTIONS_CSV        = os.path.join(OUTPUTS_ROOT, "predictions", "finalPrediction.csv")
PAPER_SUMMARY_JSON     = os.path.join(OUTPUTS_ROOT, "metrics", "paper_summary.json")
FIGURES_DIR            = os.path.join(OUTPUTS_ROOT, "figures")

# ── Model features and target ─────────────────────────────────────────────────
KEYWORDS = ["CalFresh", "FoodBank", "FoodStamps", "SNAPTopic"]

# Base features used at prediction time (no lags — future data unavailable)
# Also used as fallback if features.csv has not been built yet.
BASE_FEATURE_COLS = [
    "Population",
    "Median_Income",
    "monthly_average_CalFresh",
    "monthly_average_FoodBank",
    "monthly_average_FoodStamps",
    "monthly_average_SNAPTopic",
    "month",
]

# Deployable feature list used by stages 3 and 4 (train + evaluate).
# SNAP-derived lag/rolling features are intentionally excluded because official
# SNAP outcomes are delayed in deployment.  The model uses demographics,
# Google Trends lags/rolling/momentum, BLS LAUS unemployment, and seasonality.
FEATURE_COLS = [
    "Population", "Median_Income",
    "calfresh_lag1", "calfresh_lag2",
    "foodbank_lag1", "foodbank_lag2",
    "foodstamps_lag1", "foodstamps_lag2",
    "snaptopic_lag1", "snaptopic_lag2",
    "calfresh_roll3", "foodbank_roll3",
    "foodstamps_roll3", "snaptopic_roll3",
    "calfresh_momentum", "foodbank_momentum",
    "foodstamps_momentum", "snaptopic_momentum",
    "unemployment_rate", "unemployment_rate_lag1",
    "month_sin", "month_cos", "quarter", "month",
    "log_population", "log_income",
]

# Which CSV stages 3 and 4 read from
MODELLING_CSV = FEATURES_CSV  # set to TRAINING_DATA_CSV to use base features only

TARGET_COL = "SNAP_Application_Rate"  # = SNAP_Applications / Population

# ── XGBoost tuned hyperparameters ─────────────────────────────────────────────
# Tuned for the deployable no-SNAP-lag feature set in
# experiments/tune_deployable_model.py.
XGBOOST_PARAMS = dict(
    n_estimators=799,
    max_depth=9,
    learning_rate=0.056808,
    min_child_weight=4,
    subsample=0.8729982015899902,
    colsample_bytree=0.6559009934437239,
    reg_lambda=1.9993115185633124,
    reg_alpha=0.014724539502011025,
    random_state=42,
    n_jobs=-1,
)

# ── Walk-forward validation settings ─────────────────────────────────────────
# Minimum months of history required before the first test window opens.
# With monthly SNAP data, 12 months gives the model a full seasonal cycle to learn from.
WALK_FORWARD_MIN_MONTHS = 12

# ── Data cleaning ─────────────────────────────────────────────────────────────
# Rows where SNAP_Applications > OUTLIER_THRESHOLD × county median are dropped.
# Catches data-entry spikes (e.g. Madera Jan 2023: 11,090 vs typical ~1,000).
OUTLIER_THRESHOLD = 5.0

# ── Convenience: ensure all output directories exist ─────────────────────────
def ensure_output_dirs():
    for d in [
        os.path.join(OUTPUTS_ROOT, "data"),
        os.path.join(OUTPUTS_ROOT, "models"),
        os.path.join(OUTPUTS_ROOT, "metrics"),
        os.path.join(OUTPUTS_ROOT, "predictions"),
        FIGURES_DIR,
    ]:
        os.makedirs(d, exist_ok=True)
